export const INGREDIENT         = 'INGREDIENT';
export const INGREDIENT_LOADING = 'INGREDIENT_LOADING';

export const RECIPE_ALL         = 'RECIPE_ALL';
export const RECIPE_ALL_LOADING = 'RECIPE_ALL_LOADING';

export const RECIPE_BY_INGREDIENT         = 'RECIPE_BY_INGREDIENT';
export const RECIPE_BY_INGREDIENT_LOADING = 'RECIPE_BY_INGREDIENT_LOADING';

export const RECIPE_BY_FOLLOW_USER         = 'RECIPE_BY_FOLLOW_USER';
export const RECIPE_BY_FOLLOW_USER_LOADING = 'RECIPE_BY_FOLLOW_USER_LOADING';

export const RECIPE_BY_POPULAR         = 'RECIPE_BY_POPULAR';
export const RECIPE_BY_POPULAR_LOADING = 'RECIPE_BY_POPULAR_LOADING';

export const SEARCH_REICPE         = 'SEARCH_REICPE';
export const SEARCH_REICPE_LOADING = 'SEARCH_REICPE_LOADING';

export const RECIPE_BY_FAVORITE         = 'RECIPE_BY_FAVORITE';
export const RECIPE_BY_FAVORITE_LOADING = 'RECIPE_BY_FAVORITE_LOADING';

export const RECIPE_BY_USER_ID         = 'RECIPE_BY_USER_ID';
export const RECIPE_BY_USER_ID_LOADING = 'RECIPE_BY_USER_ID_LOADING';
