export const GET_USER         = 'GET_USER';
export const GET_USER_LOADING = 'GET_USER_LOADING';

export const GET_USER_FOLLOWING         = 'GET_USER_FOLLOWING';
export const GET_USER_FOLLOWING_LOADING = 'GET_USER_FOLLOWING_LOADING';

export const GET_USER_FOLLOW         = 'GET_USER_FOLLOW';
export const GET_USER_FOLLOW_LOADING = 'GET_USER_FOLLOW_LOADING';

export const FOLLOW_USER         = 'FOLLOW_USER';
export const FOLLOW_USER_LOADING = 'FOLLOW_USER_LOADING';

export const UNFOLLOW_USER         = 'UNFOLLOW_USER';
export const UNFOLLOW_USER_LOADING = 'UNFOLLOW_USER_LOADING';