export const LIST_RECIPE_DETAIL         = 'LIST_RECIPE_DETAIL';
export const LIST_RECIPE_DETAIL_LOADING = 'LIST_RECIPE_DETAIL_LOADING';

export const LIST_RECIPE_ADD         = 'LIST_RECIPE_ADD';
export const LIST_RECIPE_ADD_LOADING = 'LIST_RECIPE_ADD_LOADING';

export const LIST_RECIPE_UPDATE         = 'LIST_RECIPE_UPDATE';
export const LIST_RECIPE_UPDATE_LOADING = 'LIST_RECIPE_UPDATE_LOADING';

export const LIST_RECIPE_MANAGEMENT         = 'LIST_RECIPE_MANAGEMENT';
export const LIST_RECIPE_MANAGEMENT_LOADING = 'LIST_RECIPE_MANAGEMENT_LOADING';

export const LIST_RECIPE_DELETE         = 'LIST_RECIPE_DELETE';
export const LIST_RECIPE_DELETE_LOADING = 'LIST_RECIPE_DELETE_LOADING';