export const RECIPE_DETAIL         = 'RECIPE_DETAIL';
export const RECIPE_DETAIL_LOADING = 'RECIPE_DETAIL_LOADING';

export const RECIPE_ADD         = 'RECIPE_ADD';
export const RECIPE_ADD_LOADING = 'RECIPE_ADD_LOADING';

export const RECIPE_UPDATE         = 'RECIPE_UPDATE';
export const RECIPE_UPDATE_LOADING = 'RECIPE_UPDATE_LOADING';

export const RECIPE_MANAGEMENT         = 'RECIPE_MANAGEMENT';
export const RECIPE_MANAGEMENT_LOADING = 'RECIPE_MANAGEMENT_LOADING';

export const RECIPE_DELETE         = 'RECIPE_DELETE';
export const RECIPE_DELETE_LOADING = 'RECIPE_DELETE_LOADING';

export const RECIPE_COMMENTS         = 'RECIPE_COMMENTS';
export const RECIPE_COMMENTS_LOADING = 'RECIPE_COMMENTS_LOADING';

export const RECIPE_COMMENT_POST         = 'RECIPE_COMMENT_POST';
export const RECIPE_COMMENT_POST_LOADING = 'RECIPE_COMMENT_POST_LOADING';

export const RECIPE_COMMENT_DELETE         = 'RECIPE_COMMENT_DELETE';
export const RECIPE_COMMENT_DELETE_LOADING = 'RECIPE_COMMENT_DELETE_LOADING';

export const RECIPE_COMMENT_UPDATE         = 'RECIPE_COMMENT_UPDATE';
export const RECIPE_COMMENT_UPDATE_LOADING = 'RECIPE_COMMENT_UPDATE_LOADING';

export const RECIPE_LIKE         = 'RECIPE_LIKE';
export const RECIPE_LIKE_LOADING = 'RECIPE_LIKE_LOADING';

export const RECIPE_UNLIKE         = 'RECIPE_UNLIKE';
export const RECIPE_UNLIKE_LOADING = 'RECIPE_UNLIKE_LOADING';

export const ADD_RECIPE_TO_LIST         = 'ADD_RECIPE_TO_LIST';
export const ADD_RECIPE_TO_LIST_LOADING = 'ADD_RECIPE_TO_LIST_LOADING';

export const REMOVE_RECIPE_TO_LIST         = 'REMOVE_RECIPE_TO_LIST';
export const REMOVE_RECIPE_TO_LIST_LOADING = 'REMOVE_RECIPE_TO_LIST_LOADING';

export const SWITCH_RECIPE_STATUS         = 'SWITCH_RECIPE_STATUS';
export const SWITCH_RECIPE_STATUS_LOADING = 'SWITCH_RECIPE_STATUS_LOADING';