export const RECIPE_DETAIL         = 'RECIPE_DETAIL';
export const RECIPE_DETAIL_LOADING = 'RECIPE_DETAIL_LOADING';

export const RECIPE_COMMENTS         = 'RECIPE_COMMENTS';
export const RECIPE_COMMENTS_LOADING = 'RECIPE_COMMENTS_LOADING';

export const RECIPE_COMMENT_POST         = 'RECIPE_COMMENT_POST';
export const RECIPE_COMMENT_POST_LOADING = 'RECIPE_COMMENT_POST_LOADING';